### ISSUE TITLE
how to fix the position of memory status

### ISSUE THREAD

**Issue by daemoncaelum** [yuvipanda/nbresuse#14]
when it shows me, it keep on the far away from the window, and hiding behind scroll.
i will add the picture, then could see this?

and could you tell me how to fix it up?
![image](https://user-images.githubusercontent.com/30580867/55207112-516a6580-521c-11e9-8de6-a25b6824ad9c.png)
above one is when the small window size.

i want to use full screen of window, then it goes away from the view.
![image](https://user-images.githubusercontent.com/30580867/55207192-8ecef300-521c-11e9-9003-15bfb7c01dba.png)

how to fix the position of that memory status under Python 3 mark or something?

please help me

**Comment by krinsman** [comment]
@daemoncaelum  What version of Jupyter Notebook or JupyterLab are you using?

It looks like there are a lot of non-standard nbextensions installed -- each nbextension adds its own Javascript to the web page, and each extra piece of Javascript has the potential to conflict with that created by NBResuse. So there does not seem to be enough information above in order to diagnose the issue.

NBResuse currently only supports a GUI for Jupyter Notebook classic as a legacy feature, and the long-term goal is to focus on standardizing the server extension's "API" to make it as easy as possible for JupyterLab extension developers to create JupyterLab GUI's utilizing information from NBResuse. So enhancements to the Jupyter Notebook classic GUI are not low priority, especially when the issue revolves around non-standard nbextensions.

PR's fixing this issue would be welcomed of course, but we are unlikely to fix it ourselves without an external contribution.

**Comment by Betristor** [comment]
![image](https://user-images.githubusercontent.com/55777837/161414567-33f78410-2a25-4a08-979c-3152b0444594.png)
I'm a heavy extension user, and this happened just the same as described above. I wish the position could be fixed at the right side of browser, but it seems now it's conflicting with other extensions and shows in the middle.
