### ISSUE TITLE
How to access memory usage metrics with Prometheus?

### ISSUE THREAD

**Issue by mrjoseph84** [yuvipanda/nbresuse#28]
I'd be interested in using this extension to pull some memory usage related metrics to Prometheus, but I could not find any mention in the Wiki page on how to do it. Could anyone add a couple of lines with instruction and endpoint address? Thanks!

**Comment by krinsman** [comment]
To be honest I don't understand very well the Prometheus features of NBResuse, @Tommassino do you want to comment?

**Comment by mrjoseph84** [comment]
@krinsman I guess we got misunderstood a bit - all I would like to achieve is to pull the metrics that are generated NBResuse with Prometheus. Question is - how I can do it? Is there any endpoint I should reach to? For example, the standard JupyterHub metrics are published at `http://<jupyter_hub_host>:8000/hub/metrics`. So where are the NBResuse ones?...

**Comment by krinsman** [comment]
I agree, I definitely misunderstood. I still don't understand what it means to pull metrics with Prometheus.

I think NBResuse uses Prometheus now to track metrics, but since I don't understand or know anything about Prometheus I'm not really competent to say anything else. I think both the older NBResuse and the Prometheus-using NBResuse use the `metrics` endpoint, as you mentioned, to post the metrics as a JSON. However, I believe it would be necessary to confirm with @Tommassino or consult the source code, since unfortunately I do not understand the Prometheus-related portions of the source code myself.

Also to clarify I am not referring to the latest version of NBResuse available on PyPI (that does not use Prometheus), I am referring to the version in the GitHub master (that does use Prometheus).

**Comment by krinsman** [comment]
@mrjoseph84 The answer seems to depend on which version you're using, but if you are using 0.3.4 or later on PyPI, integration with Prometheus should be built-in, so the nbresuse metrics should be displayed at the Prometheus endpoint along with all of the other prometheus metrics.

I am closing this issue provisionally since it seems like your question might have been answered, but please let me know if it should be reopened.
