### ISSUE TITLE
JupyterLab regression

### ISSUE THREAD

**Issue by krinsman** [yuvipanda/nbresuse#36]
JupyterLab expects the memory usage information from NBResuse (i.e. what's waiting for it at the `<base_url>/metrics` endpoint) to have the JSON format specified by the [following interface](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/packages/statusbar/src/defaults/memoryUsage.tsx#L269):

```
  export interface IMetricRequestResult {
    rss: number;
    limits: {
      memory?: {
        rss: number;
        warn?: number;
      };
    };
  }
```

However, after the update to use Prometheus (0.3.4+), the JSON response emitted "by NBResuse" (i.e. at the `<base_url>/metrics` endpoint) is now of the form as Prometheus's HTTP API, see [here](https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview). So JupyterLab can't read it, so thinks NBResuse isn't installed, and thus no longer displays memory usage information even when NBResuse is installed.

There seems to be a fairly clear mapping between the arguments passed to the constructors of the Prometheus `Gauge`'s [here in the NBResuse code](https://github.com/yuvipanda/nbresuse/blob/edafd634a4aa852636fec32d03ce1f850d2dfff6/nbresuse/prometheus.py#L22) and the response of the [metadata portion of the Prometheus HTTP API](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata), but I'm not sure about the format of the HTTP response encoding the actual values of the metrics. That knowledge seems to be embedded implicitly in the [Javascript code for the NBExtension](https://github.com/yuvipanda/nbresuse/blob/edafd634a4aa852636fec32d03ce1f850d2dfff6/nbresuse/static/main.js#L58), but I still feel I need to look into it more closely to be sure.

Since this is a feature regression, I think it should be a priority to find some way to fix this as soon as possible, although it will probably require making a PR to JupyterLab. If that's the case, then we should probably hold off on making any such PR before stabilizing the "API" for NBResuse.

**Comment by GlennHD** [comment]
@krinsman , you appear to know a lot more about this than I do... I'm running JupyterHub and had the same issue.  It was a bit frustrating that it didn't work at first and I ran a bunch of things to no avail last night... I logged back into Jupyterhub today and the memory is showing up fine.  I wish I remembered exactly what I did but I didn't take good notes.  I just remember doing the below at one point and rebooting the machine today sometime.  Hope this leads to some solution... good luck.
```
sudo -E pip3 install nbresuse[resources]
sudo -E pip3 install psutil
```

**Comment by jtpio** [comment]
It sounds like it would be better to wait a bit for the new API (Prometheus response) to stabilize before making the changes in JupyterLab.

Maybe it's possible to deprecate the 0.3.4 version on PyPI? Since it's a breaking change, bumping to `0.4.0` or even `1.0.0` would give the different frontends some time and security to update to newer versions of nbresuse.

As a side note, the conda forge bot didn't pick up the new release and hence didn't create a new PR on the feedstock: https://github.com/conda-forge/nbresuse-feedstock

In the meantime, users can pin `nbresuse` to `0.3.3` so it works in JupyterLab (and with the [system-monitor extension](https://github.com/jtpio/jupyterlab-system-monitor)).

**Comment by jtpio** [comment]
Also looking briefly at the [code for the classic notebook extension](https://github.com/yuvipanda/nbresuse/blob/bfffb680712ba3e194fad759376c2e144ef12328/nbresuse/static/main.js), it looks like the warning (red background color) is not displayed anymore?

**Comment by jtpio** [comment]
> Maybe it's possible to deprecate the 0.3.4 version on PyPI?

This is referred to as "yanking" on PyPI:

![image](https://user-images.githubusercontent.com/591645/80367192-ee1d8d80-888a-11ea-9eed-12fc94f2ab3d.png)

**Comment by jtpio** [comment]
@krinsman should we proceed to the yanking of 0.3.4 and re-release the Prometheus changes as 0.4.0?

**Comment by jtpio** [comment]
Also I wonder if the original API should be kept alongside the prometheus response.

Working with a JSON response sounds more natural than parsing the plain text Prometheus metrics with regexes. It might also facilitate the eventual switch to EventSource (https://github.com/yuvipanda/nbresuse/pull/19).

**Comment by yuvipanda** [comment]
I added @jtpio to the repo on PyPI, and here too.

**Comment by blink1073** [comment]
I think that nbresuse should add handlers to both endpoints for backwards compatibility for at least one minor version, otherwise it is causing headaches for users.

**Comment by jtpio** [comment]
Thanks @yuvipanda. However it looks like I am unable to yank 0.3.4 (the manage button is disabled):

![image](https://user-images.githubusercontent.com/591645/84428846-78496780-ac27-11ea-9701-f5337c962c78.png)

**Comment by jtpio** [comment]
@blink1073 how about:

- merging https://github.com/yuvipanda/nbresuse/pull/45, which brings the old API back (and expose `/metrics`)
- yank 0.3.4 since it contains breaking changes (so no one gets it by mistake anymore)
- release 0.3.5 with the old `/metrics` API (so JupyterLab and other frontends can pick it up like before)

**Comment by jtpio** [comment]
This will probably bring back the issue of shadowing the default Prometheus metrics that https://github.com/yuvipanda/nbresuse/pull/22 was trying to solve.

**Comment by blink1073** [comment]
I don't think you need to necessarily yank 0.3.4 if you put out 0.3.5, if there was nothing wrong with it on its own.  I agree that `/metrics` should be deprecated and we should move away from it ASAP.  That would include a releases of JupyterLab 2.1.x that supported both endpoints.

**Comment by jtpio** [comment]
`nbreuse==0.3.5` has just been released.

This should fix the compatibility issue with JupyterLab and bring back the memory usage indicator:

![image](https://user-images.githubusercontent.com/591645/84505582-433c2400-acbe-11ea-8dc4-d4eed192d71c.png)

To update:

```
pip install -U nbresuse
```

**Comment by blink1073** [comment]
Thanks @yuvipanda and @jtpio !

**Comment by BobCashStory** [comment]
@yuvipanda i installed the latest but the CPU doesn't come in `/metrics` 
My config
```
        c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
        c.NotebookApp.ResourceUseDisplay.mem_warning_threshold = 0.1
        c.NotebookApp.ResourceUseDisplay.cpu_warning_threshold = 0.1
        c.NotebookApp.ResourceUseDisplay.cpu_limit = 1.0
        c.KubeSpawner.cpu_guarantee = 0.3
        c.KubeSpawner.cpu_limit = 1.0
        c.KubeSpawner.mem_limit = '4G'
        c.KubeSpawner.mem_guarantee = '500M'
```
i have check the code of the extension and nothing look wrong, even if i use psutil in a jupyter cell like that 
```
import psutil
psutil.cpu_percent(interval=1, percpu=True)
```
I get results, i'm a bit lost

**Comment by JohnPaton** [comment]
Is this supposed to be fixed in 0.4.0? I'm using `jupyterlab==2.2.9` and I don't get any memory status with `nbresuse==0.4.0`, but `0.3.6` works fine.

**Comment by jtpio** [comment]
@JohnPaton `0.4.0` requires enabling the deprecated endpoint manually for JupyterLab 2.x to be able to show the memory status.

Does this section in the changelog work in your setup?

https://github.com/jupyter-server/jupyter-resource-usage/blob/master/CHANGELOG.md#migrating-to-040

**Comment by JohnPaton** [comment]
Ah, I missed this, sorry. A bit of a shame that this is "broken by default" for Jupyter Lab but I get that deprecations can be bumpy. Will this be updated in a newer version?

**Comment by jtpio** [comment]
Right. Although `0.4.0` is considered a major release, so it's a good time to start adding breaking changes.

The plan is to drop it completely for the next major release: #75 

The memory status code has already been removed from core lab: https://github.com/jupyterlab/jupyterlab/pull/9386

And for JupyterLab 3.0 users will still be able to get the memory usage status item with a single `pip install`, since the lab extension will be distributed with pip as well: https://github.com/jupyter-server/jupyter-resource-usage/pull/69

So there is no dependencies between JupyterLab and nbresuse anymore, and the frontend extensions will use the new endpoint directly.
