### ISSUE TITLE
Document the soft-deprecated endpoint

### ISSUE THREAD

**Issue by jtpio** [yuvipanda/nbresuse#70]
https://github.com/yuvipanda/nbresuse/pull/68 switches the main endpoint to `/api/metrics/v1`, but keeps the original `/metrics` under a flag.

This should be documented, for example in a new CHANGELOG.md.

Also previous releases of JupyterLab 1.x and 2.x include a status bar item that requests metrics from the deprecated `/metrics` endpoint. It can be tricky to understand which versions of lab and nbresuse are compatible. However https://github.com/yuvipanda/nbresuse/pull/69 should help with this in the long run.

This is less problematic for classic notebook users since the frontend ships with `nbresuse` (https://github.com/yuvipanda/nbresuse/pull/69 would do the same for the lab frontend)

**Comment by Gsbreddy** [comment]
@jtpio I have some notes that can help. 

01.0
- Initial Commits for mem usage display

0.2.0
- Configurable memory usage warnings
- More configurability via traitlets
- Document memory limit behavior
- Add screenshot for memory usage warning
- Change 'Mem' prefix in display to less cryptic 'Memory'
- Fix primary screenshot to show memory limit too
- Consolidate code into single file

0.3.0
- Automatically install & enable extensions
- Put nbextension / serverextension enables in different places 
- Put nbresuse js files in appropriate path 

0.3.1
- Don't poll in background, since user does not see it
- Poll instantly once page is foregrounded

This should reduce the number of /metrics requests massively,
with minimal interruption to user experience.

0.3.2
- Require authentication for /metrics API Handler

0.3.3
- Made memory limit possibly dynamic via passing a callable in the config.
- Track CPU usage (#21)

0.3.4
- report the memory usage metrics as prometheus metrics
- Add section about CPU usage to the README
- Autoformatting and documentation
- Make psutil optional dependency of NBResuse

**Comment by jtpio** [comment]
Thanks a lot @Gsbreddy!

Would you like to open a PR to create CHANGELOG.md with this content?

Also we'll probably want to:

- Sort in descending order
- Include 0.3.5 and 0.3.6 too

**Comment by Gsbreddy** [comment]
Sure thing. Let me do that and get back to you.

**Comment by jtpio** [comment]
FYI @Gsbreddy https://github.com/yuvipanda/nbresuse/pull/71 adds the CHANGELOG.md, but only lists 0.4.0.

**Comment by Gsbreddy** [comment]
Sure, I will add other versions by EOD.

**Comment by Gsbreddy** [comment]
@jtpio Updated older versions in https://github.com/yuvipanda/jupyter-resource-usage/pull/72
